import { EngagementRequest } from '../types';
import { splitAmount, PLATFORM_FEE_PCT } from './payments';

// Template only - have a lawyer review before real commercial use.
export function buildLicenseAgreement(e: EngagementRequest, certificateId?: string) {
  const { fee, net } = splitAmount(e.proposedBudget);
  const date = new Date().toISOString().split('T')[0];
  const cert = certificateId || e.submission?.licenseCertificateId || 'PENDING';
  return `COMMERCIAL COPYRIGHT TRANSFER & LICENSE AGREEMENT
Certificate ID: ${cert}
Date: ${date}

PARTIES
  Client (Brand): ${e.brandName}
  Creator:        ${e.creatorName}
  Platform:       Kampus AI Creator Marketplace (intermediary)

PROJECT
  Title: ${e.briefTitle}
  Content type: ${e.contentType} | Aspect ratio: ${e.aspectRatio}
  Fee: $${e.proposedBudget.toLocaleString()} (platform fee ${PLATFORM_FEE_PCT}% = $${fee.toLocaleString()}; creator net $${net.toLocaleString()})

1. ASSIGNMENT. On receipt of final payment from escrow, Creator assigns to Client all rights, title and interest in the delivered deliverables, to the extent such rights exist under applicable law.
2. AI DISCLOSURE. Creator confirms the deliverables were produced with generative AI tools. Creator has listed the tools/models used and warrants a lawful right to use them commercially.
3. TRAINING DATA & MODELS. Creator warrants use of commercially licensed or permissively licensed models and no intentional replication of third-party protected works, logos or real persons without consent.
4. DELIVERY BOX. Prompts, seed values and workflow files are released to Client only after final payment clears.
5. CONFIDENTIALITY. ${e.ndaRequired ? 'Both parties are bound by the NDA signed on ' + (e.ndaSignedAt || 'acceptance') + '.' : 'Project details are confidential unless Client approves publication.'}
6. PORTFOLIO RIGHT. Creator may show non-confidential excerpts in their portfolio unless Client restricts this in writing.
7. INDEMNITY. Creator indemnifies Client against third-party IP claims arising from Creator's breach of clause 3.
8. GOVERNING LAW. Governed by the laws agreed in the project terms; disputes go first to platform mediation.

SIGNATURES
  Client:  ${e.brandName}   - electronically signed ${e.submission?.clientSigned ? date : '(pending)'}
  Creator: ${e.creatorName} - electronically signed ${e.status === 'completed' || e.submission ? date : '(pending)'}

This document is a template generated by the platform and is not legal advice.`;
}
